DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import re_path as url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MyWork/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views as home_views
from chat import views  as chat_views # 这里添加了chat的views
from liuyan import views as liuyan_views
from echart import views as echart_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('chat/',chat_views.chat,name='chat'),
    path('',home_views.get_weather,name='weather'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liuyan/', liuyan_views.recruit, name='liuyan'),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('jishu/',include('jishu.urls')),
    path('ziliao/',include('ziliao.urls')),
    path('suibi/',include('suibi.urls')),
    path('echart/',include('echart.urls')),
]

jishu/urls.py
from django.urls import path
from . import views

app_name='jishu'

urlpatterns=[
    path('jishu/<str:jishuName>', views.jishu, name='jishu'),
    path('jishuDetail/<int:id>/', views.jishuDetail, name='jishuDetail'),
    path('search/',views.search,name='search')
]

suibi/urls.py
from django.urls import path
from . import views

app_name='suibi'

urlpatterns=[
    path('note/', views.note, name='note'),
    path('noteDetail/<int:id>/', views.noteDetail, name='noteDetail'),
    path('search/',views.search,name='search')
]

ziliao/urls.py
from django.urls import path
from . import views
app_name='ziliao'
urlpatterns=[
    path('download/',views.download,name='download'),
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
    path('search/',views.search,name='search'),

]

home/models.py
from django import forms

home/views.py
from django.contrib.sites import requests

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login


from jishu.models import Myjishu
from django.db.models import Q   #查询函数

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('')
        else:
            # 登录失败的处理逻辑，例如显示错误消息
            error_message = "用户名或密码不正确"
            return render(request, 'home.html', {'error_message': error_message})

    return render(request, 'home.html')




import requests
from django.shortcuts import render

def get_weather(request):
    if request.method == 'POST':
        print(request.POST)
        api_key = "S25gERTOkgOZvz9Qa"
        location = request.POST.get('city')  # 获取前端输入的城市名称
        print(location)
        api_url = f"https://api.seniverse.com/v3/weather/now.json?key={api_key}&location={location}"

        response = requests.get(api_url)
        data = response.json()

        if response.status_code == 200:
            result = data["results"][0]
            location = result["location"]
            now = result["now"]

            weather_info = {
                "city": location["name"],
                "country": location["country"],
                "text": now["text"],
                "temperature": now["temperature"],
                # "feels_like": now["feels_like"],
                # "pressure": now["pressure"],
                # "wind_direction": now["wind_direction"],
                # "visibility": now["visibility"],
                # "humidity": now["humidity"],
            }

            return render(request, 'home.html', {'weather_info': weather_info})
        else:
            error_message = "请求失败"
            return render(request, 'home.html', {'error_message': error_message})
        # 新闻里，不是通知公告的
    jishuList = Myjishu.objects.all().filter(~Q(jishuType='Python')).order_by('-publishDate')
    postList = set()
    postNum = 0
    for s in jishuList:
        if s.photo:  # 有展报
            postList.add(s)
            postNum += 1
            print('有')
        if postNum == 3:  # 只截取最近的3个展报
            break

    # 新闻列表
    if (len(jishuList) > 7):
        jishuList = jishuList[0:7]  # 7条新闻

    noteList = Myjishu.objects.all().filter(
        ~Q(jishuType='Nosql')).order_by('-publishDate')
    if (len(noteList) > 4):
        noteList = noteList[0:4]
    return render(request, 'home.html',
                  {'active_menu': 'home',
                   'postList': postList,
                   'jishuList': jishuList,
                   'noteList': noteList,
                   })

home/templates/home.html
{% extends "base.html" %}
{% block title %}
    首页
{% endblock %}
{% block content %}
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
     <style>
        body, html {
            height: 100%;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
            text-align: center;
            font-size: 24px;
        }
        .weather-info {
        margin-bottom: 10px;

    }
.title {
    margin-top: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
}
        .title h2 {
            margin-top: 10px;
    font-size: 16px;
    font-weight: normal;
    width: 80px;
}

        .widget_links li a {

    padding: 5px 8px;
    display: inline-block;
    width: 80%;
    text-align: center;
}
        a {
    color: #00a67c;

}
       .h2 {
        display: flex;
        align-items: center;
    }
  .tag-container {
    display: flex;
    justify-content: center;
      margin-left: 10px;
      margin-top: 10px;
  }

  .tag-container a {
    flex: 1;
    text-align: center;
  }

  .h1-1 {
            font-family: 'Pacifico', cursive;
            font-size: 30px;
            color: #333;
            margin-left: 180px;
            text-transform: uppercase;
        }

  .larger-badge {
    display: block;
    font-size: 8px;
    padding: 5px 12px;
  }
    </style>


    {% if not user.is_authenticated %}
        <div class="container">
            <p>您还没有登录，请点击右上角的按钮登录！</p>
        </div>

    {% else %}
    <div class="layui-container">
    <div class="layui-row">
    <div class="layui-col-md8">
 <h1 class="h1-1">个人博客网站简介</h1>
        <div class="layui-carousel" id="test3" lay-filter="test4"style="margin-top: 5px">
    <div carousel-item="">
       <div><img src="/layui/img/1.png" style="max-width: 100%; height: auto"></div>
        <div><img src="/layui/img/java.jpeg" style="max-width: 100%; height: auto"></div>
        <div><img src="/layui/img/python.jpeg" style="max-width: 100%; height: auto"></div>
        <div><img src="/layui/img/html.jpeg" style="max-width: 100%; height: auto"></div>
    </div>
</div>
    <h2 style="margin-left: 150px;margin-top: 30px">欢迎来到我的个人博客网站！</h2>
    <p style="margin-right: 120px;font-size: 15px">     在这个快节奏的时代，我们往往被工作和生活的琐事所紧紧束缚，很少有机会静下心来思考和交流。然而，思考和交流是我们个体和社会发展的重要组成部分。我的个人博客网站致力于提供一个平台，让我们一起思考、探索和分享。

这里，您将找到关于生活、哲学、科技、艺术和旅行等各种主题的文章。我将分享我对这些领域的观点和见解，同时也欢迎您的反馈和讨论。我相信，通过相互的交流和碰撞，我们可以激发出更多灵感和思考，从而不断成长和进步。

除了文字，我的个人博客网站还提供丰富的多媒体内容。您可以欣赏到精心拍摄的照片、制作的视频以及其他艺术形式的展示。通过视觉和听觉的感受，我们可以更深入地理解和表达思想，让信息更加生动和丰富。

我的个人博客网站也是一个互动的平台。您可以在文章下方留下您的评论和想法，与我以及其他读者进行交流。我非常重视您的声音，每一条评论都将得到我的认真回复。让我们一起建立一个积极、尊重和开放的社区，共同创造有价值的讨论和分享。

最后，我希望我的个人博客网站能够成为您的心灵驿站。无论您是追求思想启示、寻找灵感的艺术家，还是对生活和世界充满好奇的冒险家，这里都将为您提供丰富的资源和独特的视角。让我们一起踏上这个探索无限可能性的旅程！

感谢您的光临，期待与您共同分享和成长！</p>
        <p style="margin-right: 120px;font-size: 15px">联系方式：zihang0266@gmail.com</p>

    </div>
    <div class="layui-col-md4 " >
      <h2 class="h2" style="margin-top: 20px">天气查询 <i class="layui-icon layui-icon-light" style="font-size: large"></i>   </h2>

    <form method="post" action="{% url 'weather' %}">
        {% csrf_token %}
        <label for="city">输入城市名：</label>
        <input type="text" id="city" name="city" required>
        <button type="submit">查询</button>
    </form>

    {% if weather_info %}
        <h2>天气信息</h2>
        <p class="weather-info">国家: {{ weather_info.country }} 城市: {{ weather_info.city }}</p>
        <p class="weather-info">天气现象: {{ weather_info.text }}</p>
        <p class="weather-info">温度：{{ weather_info.temperature }} ℃ </p>
    {% endif %}

    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <hr class="layui-border-green">
    <div class="widget widget_links">
        <div class="title"><h2>友情链接</h2></div>
        <hr class="layui-border-green">
        <ul class="xoxo blogroll" style="width: 332px; display: flex; flex-wrap: wrap;">
    <li style="width: 50%;"><a href="https://www.csdn.net" target="_blank">csdn</a></li>
    <li style="width: 50%;"><a href="https://github.com" target="_blank">GitHub</a></li>
    <li style="width: 50%;"><a href="https://stackoverflow.com" rel="acquaintance" target="_blank">Stack Overflow</a></li>
    <li style="width: 50%;"><a href="https://developer.mozilla.org" target="_blank">MDN Web Docs</a></li>
    <li style="width: 50%;"><a href="https://www.coursera.org" target="_blank">Coursera</a></li>
    <li style="width: 50%;"><a href="https://www.codecademy.com" target="_blank">Codecademy</a></li>
    <li style="width: 50%;"><a href="https://medium.com">Medium</a></li>
    <li style="width: 50%;"><a href="https://news.ycombinator.com">Hacker News</a></li>
    <li style="width: 50%;"><a href="https://www.theverge.com">The Verge</a></li>
    <li style="width: 50%;"><a href="https://dev.to">Dev.to</a></li>
    <li style="width: 50%;"><a href="https://www.w3schools.com">W3Schools</a></li>
</ul>
    <div class="widget d_tag">
        <div class="title"><h2>分类标签</h2></div>
        <hr class="layui-border-green">
        <div class="d_tags" id="fenlei" style="height: auto">
            <div class="tag-container">
              <a href="{% url 'jishu:jishu' 'Python' %}">
                <span class="layui-badge larger-badge">Python</span>
              </a>
              <a href="{% url 'jishu:jishu' '大数据' %}">
                <span class="layui-badge layui-bg-orange larger-badge">大数据</span>
              </a>
            </div>
            <div class="tag-container">
              <a href="{% url 'jishu:jishu' '金融' %}">
                <span class="layui-badge layui-bg-green larger-badge">NoSql</span>
              </a>
              <a href="{% url 'jishu:jishu' '前端' %}">
                <span class="layui-badge layui-bg-cyan larger-badge">前端</span>
              </a>
            </div>
            <div class="tag-container">
              <a href="{% url 'suibi:note' %}">
                <span class="layui-badge layui-bg-blue larger-badge">生活随笔</span>
              </a>
              <a href="{% url 'ziliao:download'  %}">
                <span class="layui-badge layui-bg-black larger-badge">资料下载</span>
              </a>
            </div>
            <div class="tag-container">
              <a href="/liuyan">
                <span class="layui-badge layui-bg-cyan larger-badge">留言板</span>
              </a>
              <a href="/chat">
                <span class="layui-badge layui-bg-orange larger-badge">chat</span>
              </a>
            </div>

            <div class="title"><h2>轮播图参数</h2></div>
        <hr class="layui-border-green">
<div class="layui-form" >
  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">宽高</label>
      <div class="layui-input-inline" style="width:98px">
        <input type="tel" name="width" value="600" autocomplete="off" placeholder="width" class="layui-input demoSet">
      </div>
      <div class="layui-input-inline" style="width: 98px;">
        <input type="tel" name="height" value="280" autocomplete="off" placeholder="height" class="layui-input demoSet">
      </div>
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">动画类型</label>
    <div class="layui-input-block">
      <div class="layui-btn-group demoTest" style="margin-top: 5px;">
        <button class="layui-btn layui-btn-sm" style="background-color: #5FB878;" data-type="set" data-key="anim" data-value="default">左右切换</button>
        <button class="layui-btn layui-btn-sm" data-type="set" data-key="anim" data-value="updown">上下切换</button>
        <button class="layui-btn layui-btn-sm" data-type="set" data-key="anim" data-value="fade">渐隐渐显</button>
      </div>
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">箭头状态</label>
    <div class="layui-input-block">
      <div class="layui-btn-group demoTest" style="margin-top: 5px;">
        <button class="layui-btn layui-btn-sm" style="background-color: #5FB878;" data-type="set" data-key="arrow" data-value="hover">悬停显示</button>
        <button class="layui-btn layui-btn-sm" data-type="set" data-key="arrow" data-value="always">始终显示</button>
        <button class="layui-btn layui-btn-sm" data-type="set" data-key="arrow" data-value="none">不显示</button>
      </div>
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">指示器位置</label>
    <div class="layui-input-block">
      <div class="layui-btn-group demoTest" style="margin-top: 5px;">
        <button class="layui-btn layui-btn-sm" style="background-color: #5FB878;" data-key="indicator" data-type="set" data-value="inside">容器内部</button>
        <button class="layui-btn layui-btn-sm" data-type="set" data-key="indicator" data-value="outside">容器外部</button>
        <button class="layui-btn layui-btn-sm" data-type="set" data-key="indicator" data-value="none">不显示</button>
      </div>
    </div>
  </div>

  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">自动切换</label>
      <div class="layui-input-block">
        <input type="checkbox" name="switch" lay-skin="switch" checked="" lay-text="ON|OFF" lay-filter="autoplay">
      </div>
    </div>
    <div class="layui-inline">
      <label class="layui-form-label" style="width: auto;">时间间隔</label>
      <div class="layui-input-inline" style="width: 120px;">
        <input type="tel" name="interval" value="3000" autocomplete="off" placeholder="毫秒" class="layui-input demoSet">
      </div>
    </div>
  </div>

</div>
</div>
    </div>
    </div>
    </div>
</div>
</div>
<script src="/layui/layui.js" charset="utf-8"></script>
    <script>
layui.use(['carousel', 'form'], function(){
  var carousel = layui.carousel
  ,form = layui.form;

  //常规轮播
  carousel.render({
    elem: '#test1'
    ,arrow: 'always'
  });

  //改变下时间间隔、动画类型、高度
  carousel.render({
    elem: '#test2'
    ,interval: 1800
    ,anim: 'fade'
    ,height: '120px'
  });

  //设定各种参数
  var ins3 = carousel.render({
    elem: '#test3'
  });
  //图片轮播
  carousel.render({
    elem: '#test10'
    ,width: '778px'
    ,height: '440px'
    ,interval: 5000
  });

  //事件
  carousel.on('change(test4)', function(res){
    console.log(res)
  });

  var $ = layui.$, active = {
    set: function(othis){
      var THIS = 'layui-bg-normal'
      ,key = othis.data('key')
      ,options = {};

      othis.css('background-color', '#5FB878').siblings().removeAttr('style');
      options[key] = othis.data('value');
      ins3.reload(options);
    }
  };

  //监听开关
  form.on('switch(autoplay)', function(){
    ins3.reload({
      autoplay: this.checked
    });
  });

  $('.demoSet').on('keyup', function(){
    var value = this.value
    ,options = {};
    if(!/^\d+$/.test(value)) return;

    options[this.name] = value;
    ins3.reload(options);
  });

  //其它示例
  $('.demoTest .layui-btn').on('click', function(){
    var othis = $(this), type = othis.data('type');
    active[type] ? active[type].call(this, othis) : '';
  });
});
</script>
    {% endif %}
{% endblock %}

home/templates/weather.html
<!-- weather.html -->

<!DOCTYPE html>
<html>
<head>
    <title>天气信息</title>
</head>
<body>
    <h1>城市：{{ weather_info.city }}</h1>
    <p>国家：{{ weather_info.country }}</p>
    <p>天气现象：{{ weather_info.text }}</p>
    <p>温度：{{ weather_info.temperature }} ℃</p>
{#    <p>体感温度：{{ weather_info.feels_like }} ℃</p>#}
{#    <p>气压：{{ weather_info.pressure }} mb</p>#}
{#    <p>风向：{{ weather_info.wind_direction }}</p>#}
{#    <p>能见度：{{ weather_info.visibility }} km</p>#}
{#    <p>湿度：{{ weather_info.humidity }} %</p>#}

    {% if weather_info.error %}
        <p>{{ weather_info.error }}</p>
    {% endif %}
</body>
</html>