DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import re_path as url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MyWork/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views as home_views
from chat import views  as chat_views # 这里添加了chat的views
from liuyan import views as liuyan_views
from echart import views as echart_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('chat/',chat_views.chat,name='chat'),
    path('',home_views.get_weather,name='weather'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liuyan/', liuyan_views.recruit, name='liuyan'),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('jishu/',include('jishu.urls')),
    path('ziliao/',include('ziliao.urls')),
    path('suibi/',include('suibi.urls')),
    path('echart/',include('echart.urls')),
]

jishu/urls.py
from django.urls import path
from . import views

app_name='jishu'

urlpatterns=[
    path('jishu/<str:jishuName>', views.jishu, name='jishu'),
    path('jishuDetail/<int:id>/', views.jishuDetail, name='jishuDetail'),
    path('search/',views.search,name='search')
]

jishu/models.py
from django.db import models
from DjangoUeditor.models import UEditorField   #富文本编辑器
import django.utils.timezone as timezone

# Create your models here.


class Myjishu(models.Model):
    jishu_CHOICES = (
        ('Python', 'Python'),
        ('前端', '前端'),
        ('大数据', '大数据'),
        ('NoSql', 'NoSql'),
    )    #元组， 不是字段
    title = models.CharField(max_length=50, verbose_name=' 技术标题')
    description = UEditorField(u'内容',     #富文本编辑器，后台中的别名
                               default='',  #内容为空
                               width=1000,
                               height=300,
                               imagePath='news/images/',  #上传图像的存储位置
                               filePath='news/files/')     #上传文件的存储位置
    jishuType = models.CharField(choices=jishu_CHOICES,   #上面定义的元组
                               max_length=50,
                               verbose_name='技术类型')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')
    views = models.PositiveIntegerField('浏览量', default=0)
    photo = models.ImageField(upload_to='news/',
                              blank=True,
                              null=True,
                              verbose_name='展报')

    def __str__(self):
        return self.title  #后台中显示新闻标题字段

    class Meta:
        ordering = ['-publishDate']
        verbose_name = "技术杂谈"
        verbose_name_plural = verbose_name

jishu/views.py
from django.shortcuts import render, get_object_or_404
from .models import Myjishu  #新闻表
from django.core.paginator import Paginator
from pyquery import PyQuery as pq

def jishu(request,jishuName):
    submenu=jishuName  #侧边导航栏的激活状态
    if jishuName=='Python':
        jishuName='Python'
    elif jishuName=='大数据':
        jishuName='大数据'
    elif jishuName=='前端':
        jishuName='前端'
    else:
        jishuName='NoSql'

    jishuList = Myjishu.objects.all().filter(
        jishuType=jishuName).order_by('-publishDate')
    for myjishu in jishuList:
        html = pq(myjishu.description)  # 使用pq方法解析html内容
        myjishu.mytxt = pq(html)('p').text()  # 截取html段落文字

    p = Paginator(jishuList, 5)  # 过滤好的数据，每页显示5条
    if p.num_pages <= 1:
        pageData = ''  # 向前端传递空串
    else:
        page = int(request.GET.get('page', 1))  # 前端页码超链接 传过来的具体页码
        jishuList = p.page(page)  # 具体页码要显示的5条记录
        left = []  # 列表
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages  # 总页数
        page_range = p.page_range  # 页数范围
        if page == 1:
            right = page_range[page:page + 2]  # 列表 right[0]=2 right[1]=3
            print(total_pages)
            if right[-1] < total_pages - 1:  # right[-1]为3
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]  # 倒数第3页，倒数第2页
            if left[0] > 2:  # 倒数第3页页码大于2
                left_has_more = True
            if left[0] > 1:
                first = True
        else:  # 不是第一页或最后一页
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageData = {  # 字典，会传给前端
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }

    return render(request,'jishuList.html',{
        'active_menu':'jishu', #base.html新闻动态所在li的id号为jishu
        'sub_menu':submenu,
        'jishuName':jishuName,
        'jishuList':jishuList,
        'pageData': pageData,})

def jishuDetail(request, id):
    myjishu = get_object_or_404(Myjishu, id=id)  # 从MyNew表中获取指定id号的新闻
    myjishu.views += 1
    myjishu.save()
    return render(request, 'jishuDetail.html', {
        'myjishu': myjishu,  # 传递给前端的模板变量
    })

def search(request):
    keyword=request.GET.get('keyword')
    jishuList=Myjishu.objects.filter(title__icontains=keyword) #标题中包含指定关键字
    jishuName="关于"+"\""+keyword+"\""+"的搜索结果"
    return render(request,'searchList.html',{
        'active_menu':'news',
        'jishuName':jishuName,
        'jishuList':jishuList,
    })

jishu/templates/jishuDetail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ jishuName }}
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
    <div class="container">
        <div class="model-details-product-title">
            {{ myjishu.title }}   <!--mynew为后台传递过来的数据-->
            <div class="model-foot">
                发布时间：{{ myjishu.publishDate|date:'Y-m-d' }} &nbsp;&nbsp;
                浏览次数：{{ myjishu.views }}
            </div>
        </div>
        <div class="model-details">
                {{ myjishu.description|safe}} <!--safe实现富文本的内容渲染-->
        </div>
    </div>
{% endblock %}

jishu/templates/jishuList.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ jishuName }}
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
    <!--主体内容-->
    <div class="container">
        <div class="row row-3">
            <!--侧边导航栏-->
            <div class="col-md-3">
                <div class="model-title">
                   技术杂谈
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="Python">
                            <a href="{% url 'jishu:jishu' 'Python' %}">Python</a>
                        </li>
                        <li class="list-group-item" id="前端">
                            <a href="{% url 'jishu:jishu' '前端' %}">前端</a>
                        </li>
                        <li class="list-group-item" id="大数据">
                            <a href="{% url 'jishu:jishu' '大数据' %}">大数据</a>
                        </li>
                        <li class="list-group-item" id="NoSql">
                            <a href="{% url 'jishu:jishu' 'NoSql' %}">NoSql</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!--产品的说明文字后和图片-->
            <div class="col-md-9">
                <div class="model-details-title">
                    {{ jishuName }}
               <div class="col-md-7 hidden-xs model-details-title-search">
                        <form method="get" action="{% url 'jishu:search'  %}">  <!--newsApp中名为search的路由-->
                            {% csrf_token %} <!--为了防止csrf（跨站请求伪造）-->
                            <div class="input-group"> <!--bootstrap-->
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询">
                                </span>
                            </div>
                        </form>
                    </div>

                </div>
                <div class="model-details">

                    {% for myjishu in jishuList %}   <!--jishuList为后台传过来的新闻数据-->
                    <div class="news-model">
                       <img src="{% static 'img/newsicon.gif' %}">
                        <a href="{% url 'jishu:jishuDetail' myjishu.id %}"> <b>{{ myjishu.title }}</b> </a>
                        <span> 【{{ myjishu.publishDate|date:"Y-m-d" }}】</span>
                        <p>
                            <!--添加新闻简要说明-->
                            {{ myjishu.mytxt|truncatechars:"110" }}...
                        </p>
                    </div>
                    {% endfor %}

            {% if pageData %}
                <div class="paging">
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if pageData.first %}
                        <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if pageData.left %}
                        {% if pageData.left_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% for i in pageData.left %}
                        <li><a href="?page={{i}}">{{i}}</a></li><!--单击时会将参数page的值封装到request中，后台从request中得到page变量值-->
                        {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{pageData.page}}">{{pageData.page}}</a></li>
                        {% if pageData.right %}
                        {% for i in pageData.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% if pageData.right_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% endif %}
                        {% if pageData.last %}
                        <li><a href="?page={{pageData.total_pages}}">{{pageData.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

jishu/templates/searchList.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ jishuName }}
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
  <div class="container">
        <div class="row row-3">
                <div class="model-details-title">
                    {{ jishuName }}
                    <div class="col-md-7 hidden-xs model-details-title-search">
                        <form method="get" action="{% url 'jishu:search'  %}">  <!--newsApp中名为search的路由-->                            		{% csrf_token %} <!--为了防止csrf（跨站请求伪造）-->
                            <div class="input-group"> <!--bootstrap-->
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询">
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="model-details">
                    {% for myjishu in jishuList %}   <!--newList为后台传过来的新闻数据-->
                    <div class="news-model">
                        <img src="{% static 'img/newsicon.gif' %}">
                        <a href="{% url 'jishu:jishuDetail' myjishu.id %}"> <b>{{ myjishu.title }}</b> </a>
                        <span> 【{{ myjishu.publishDate|date:"Y-m-d" }}】</span>
                    </div>
                    {% endfor %}
                </div>
        </div>
    </div>
{% endblock %}