DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import re_path as url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MyWork/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views as home_views
from chat import views  as chat_views # 这里添加了chat的views
from liuyan import views as liuyan_views
from echart import views as echart_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('chat/',chat_views.chat,name='chat'),
    path('',home_views.get_weather,name='weather'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liuyan/', liuyan_views.recruit, name='liuyan'),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('jishu/',include('jishu.urls')),
    path('ziliao/',include('ziliao.urls')),
    path('suibi/',include('suibi.urls')),
    path('echart/',include('echart.urls')),
]

ziliao/urls.py
from django.urls import path
from . import views
app_name='ziliao'
urlpatterns=[
    path('download/',views.download,name='download'),
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
    path('search/',views.search,name='search'),

]

ziliao/models.py
from django.db import models

import  django.utils.timezone as timezone
class Doc(models.Model):
    title = models.CharField(max_length=250, verbose_name='资料名称')
    file = models.FileField(upload_to='Service/', #上传到，   存储路径
                            blank=True,
                            verbose_name='文件资料')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publishDate']
        verbose_name = "资料"
        verbose_name_plural = verbose_name

ziliao/views.py
from django.shortcuts import render

# Create your views here.
from .models import Doc
from django.core.paginator import Paginator

def download(request):
    submenu = 'download'
    docList = Doc.objects.all().order_by('-publishDate')
    p = Paginator(docList, 3)
    if p.num_pages <= 1:
        pageData = ''
    else:
        page = int(request.GET.get('page', 1))
        docList = p.page(page)  #那一页的数据
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageData = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }
    return render(
        request, 'ziliao.html', {
            'active_menu': 'service',
            'sub_menu': submenu,
            'docList': docList,
            'pageData': pageData,
        })

def read_file(file_name, size):
    with open(file_name, mode='rb') as fp:
        while True:
            c = fp.read(size)
            if c:
                yield c
            else:
                break

from django.shortcuts import get_object_or_404
from django.http import StreamingHttpResponse #用于将文件流发送给浏览器
import os
def getDoc(request, id):
    doc = get_object_or_404(Doc, id=id)
    update_to, filename = str(doc.file).split('/')
    filepath = '%s/media/%s/%s' % (os.getcwd(), update_to, filename)
    response = StreamingHttpResponse(read_file(filepath, 512))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{}"'.format(
        filename)
    return response


def search(request):
    keyword=request.GET.get('keyword')
    doclist=Doc.objects.filter(title__icontains=keyword) #标题中包含指定关键字
    docName="关于"+"\""+keyword+"\""+"的搜索结果"
    return render(request,'searchList1.html',{
        'active_menu':'service',
        'docList':doclist,
        'docName':docName
    })

ziliao/templates/searchList1.html
{% extends "base.html" %}
{% load static %}
{% block title %}
 {{ docName }}
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
    <!--主体内容-->
    <div class="container">
        <div class="row row-3">
                <div class="model-details-title">
                    {{ docName }}
                    <div class="col-md-7 hidden-xs model-details-title-search">
                        <form method="get" action="{% url 'ziliao:search'  %}">  <!--newsApp中名为search的路由-->                            		{% csrf_token %} <!--为了防止csrf（跨站请求伪造）-->
                            <div class="input-group"> <!--bootstrap-->
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询">
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="model-details">
                    {% for doc in docList %}   <!--newList为后台传过来的新闻数据-->
                    <div class="news-model">
                        <img src="{% static 'img/newsicon.gif' %}">
                        <a href="{% url 'jiaoxueApp:getDoc' doc.id %}"><b>{{doc.title}}</b></a>
                        <span> 【{{ doc.publishDate|date:"Y-m-d" }}】</span>
                    </div>
                    {% endfor %}
                </div>
        </div>
    </div>
{% endblock %}

ziliao/templates/ziliao.html
{% extends "base.html" %}
{% load static %}
{% block title %}
资料下载
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
<!-- 主体内容 -->

<div class="container">
    <div class="row row-3">
        <!-- 侧边导航栏 -->
        <div class="col-md-3">
            <div class="model-title">
                服务支持
            </div>
            <div class="model-list">
                <ul class="list-group">
                    <li class="list-group-item" id='download'>
                        <a href="{% url 'ziliao:download' %}">资料下载</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- 说明文字和图片 -->
        <div class="col-md-9">
            <div class="model-details-title">
                资料列表
                         <div class="col-md-7 hidden-xs model-details-title-search">
                        <form method="get" action="{% url 'ziliao:search'  %}">  <!--newsApp中名为search的路由-->
                            {% csrf_token %} <!--为了防止csrf（跨站请求伪造）-->
                            <div class="input-group"> <!--bootstrap-->
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询">
                                </span>
                            </div>
                        </form>
                    </div>
            </div>
            <div class="model-details">
                {% for doc in docList %}  <!--有几项资料，就循环几次-->
                <div class="news-model">
                    <img src="{% static 'img/newsicon.gif' %}">
                    <a href="{% url 'ziliao:getDoc' doc.id %}"><b>{{doc.title}}</b></a>   <!--资料名称-->
                    <span>【{{doc.publishDate|date:"Y-m-d"}}】</span>
                </div>
                {% endfor %}

                {% if pageData %}
                <div class="paging">
                    <ul id="pages" class="pagination">
                        {% if pageData.first %}
                        <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if pageData.left %}
                        {% if pageData.left_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% for i in pageData.left %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{pageData.page}}">
                                {{pageData.page}}</a></li>
                        {% if pageData.right %}
                        {% for i in pageData.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% if pageData.right_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% endif %}
                        {% if pageData.last %}
                        <li><a href="?page={{pageData.total_pages}}">
                                {{pageData.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock%}