DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import re_path as url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MyWork/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views as home_views
from chat import views  as chat_views # 这里添加了chat的views
from liuyan import views as liuyan_views
from echart import views as echart_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('chat/',chat_views.chat,name='chat'),
    path('',home_views.get_weather,name='weather'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('liuyan/', liuyan_views.recruit, name='liuyan'),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('jishu/',include('jishu.urls')),
    path('ziliao/',include('ziliao.urls')),
    path('suibi/',include('suibi.urls')),
    path('echart/',include('echart.urls')),
]

suibi/urls.py
from django.urls import path
from . import views

app_name='suibi'

urlpatterns=[
    path('note/', views.note, name='note'),
    path('noteDetail/<int:id>/', views.noteDetail, name='noteDetail'),
    path('search/',views.search,name='search')
]

suibi/models.py
from django.db import models

# Create your models here.
from datetime import datetime
from django.utils import timezone

from DjangoUeditor.models import UEditorField   #富文本编辑器


class Mynote(models.Model):
    title = models.CharField(max_length=50, verbose_name=' 技术标题')
    description = UEditorField(u'内容',  # 富文本编辑器，后台中的别名
                               default='',  # 内容为空
                               width=1000,
                               height=300,
                               imagePath='news/images/',  # 上传图像的存储位置
                               filePath='news/files/')  # 上传文件的存储位置

    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='提交时间', null=True)
    views = models.PositiveIntegerField('浏览量', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '生活随笔'
        verbose_name_plural = '生活随笔'

suibi/views.py
from django.shortcuts import render, get_object_or_404
from .models import Mynote  #新闻表
from django.core.paginator import Paginator
from pyquery import PyQuery as pq

def note(request):
    submenu = 'note'
    noteList = Mynote.objects.all().order_by('-publishDate')
    p = Paginator(noteList, 5)
    if p.num_pages <= 1:
        pageData = ''
    else:
        page = int(request.GET.get('page', 1))
        noteList = p.page(page)  #那一页的数据
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageData = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }
    return render(
        request, 'note.html', {
            'active_menu': 'service',
            'sub_menu': submenu,
            'noteList': noteList,
            'pageData': pageData,
        })

def noteDetail(request, id):
    mynote = get_object_or_404(Mynote, id=id)  # 从MyNew表中获取指定id号的新闻
    mynote.views += 1
    mynote.save()
    return render(request, 'noteDetail.html', {
        'mynote': mynote,  # 传递给前端的模板变量
    })

def search(request):
    keyword=request.GET.get('keyword')
    noteList=Mynote.objects.filter(title__icontains=keyword) #标题中包含指定关键字
    noteName="关于"+"\""+keyword+"\""+"的搜索结果"
    return render(request,'searchList2.html',{
        'active_menu':'news',
        'noteName':noteName,
        'noteList':noteList,
    })

suibi/templates/note.html
{% extends "base.html" %}
{% load static %}
{% block title %}
生活随笔
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
    <!--主体内容-->
    <div class="container">
        <div class="row row-3">
            <!--侧边导航栏-->
            <div class="col-md-3">
                <div class="model-title">
                   笔记
                </div>
                <div class="model-list">
                    <ul class="list-group">
                        <li class="list-group-item" id="Python">
                            <a href="{% url 'suibi:note' %}">生活随笔</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!--产品的说明文字后和图片-->
            <div class="col-md-9">
                <div class="model-details-title">
                    笔记列表
               <div class="col-md-7 hidden-xs model-details-title-search">
                        <form method="get" action="{% url 'suibi:search'  %}">  <!--newsApp中名为search的路由-->
                            {% csrf_token %} <!--为了防止csrf（跨站请求伪造）-->
                            <div class="input-group"> <!--bootstrap-->
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询">
                                </span>
                            </div>
                        </form>
                    </div>

                </div>
                <div class="model-details">

                    {% for mynote in noteList %}   <!--jishuList为后台传过来的新闻数据-->
                    <div class="news-model">
                       <img src="{% static 'img/newsicon.gif' %}">
                        <a href="{% url 'suibi:noteDetail' mynote.id %}"> <b>{{ mynote.title }}</b> </a>
                        <span> 【{{ mynote.publishDate|date:"Y-m-d" }}】</span>
                        <p>
                            <!--添加新闻简要说明-->
                            {{ mynote.mytxt|truncatechars:"110" }}...
                        </p>
                    </div>
                    {% endfor %}

            {% if pageData %}
                <div class="paging">
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if pageData.first %}
                        <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if pageData.left %}
                        {% if pageData.left_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% for i in pageData.left %}
                        <li><a href="?page={{i}}">{{i}}</a></li><!--单击时会将参数page的值封装到request中，后台从request中得到page变量值-->
                        {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{pageData.page}}">{{pageData.page}}</a></li>
                        {% if pageData.right %}
                        {% for i in pageData.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% if pageData.right_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% endif %}
                        {% if pageData.last %}
                        <li><a href="?page={{pageData.total_pages}}">{{pageData.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

suibi/templates/noteDetail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ jishuName }}
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
    <div class="container">
        <div class="model-details-product-title">
            {{ mynote.title }}   <!--mynew为后台传递过来的数据-->
            <div class="model-foot">
                发布时间：{{ mynote.publishDate|date:'Y-m-d' }} &nbsp;&nbsp;
                浏览次数：{{ mynote.views }}
            </div>
        </div>
        <div class="model-details">
                {{ mynote.description|safe}} <!--safe实现富文本的内容渲染-->
        </div>
    </div>
{% endblock %}

suibi/templates/searchList2.html
{% extends "base.html" %}
{% load static %}
{% block title %}
随笔
{% endblock %}
{% block content %}
     <link href="{% static 'css/style.css' %}" rel="stylesheet" >
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/jishu.css' %}" rel="stylesheet" >
  <div class="container">
        <div class="row row-3">
                <div class="model-details-title">
                    {{ noteName }}
                    <div class="col-md-7 hidden-xs model-details-title-search">
                        <form method="get" action="{% url 'suibi:search'  %}">  <!--newsApp中名为search的路由-->                            		{% csrf_token %} <!--为了防止csrf（跨站请求伪造）-->
                            <div class="input-group"> <!--bootstrap-->
                                <input type="text" name="keyword" class="form-control" placeholder="请输入关键词" required>
                                <span class="input-group-btn">
                                    <input type="submit" class="btn btn-default" value="查询">
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="model-details">
                    {% for mynote in noteList %}   <!--newList为后台传过来的新闻数据-->
                    <div class="news-model">
                        <img src="{% static 'img/newsicon.gif' %}">
                        <a href="{% url 'suibi:noteDetail' mynote.id %}"> <b>{{ mynote.title }}</b> </a>
                        <span> 【{{ mynote.publishDate|date:"Y-m-d" }}】</span>
                    </div>
                    {% endfor %}
                </div>
        </div>
    </div>
{% endblock %}